version: "3.3"

services:
  database:
    image: postgres
    container_name: database_api
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=api
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: api
    ports:
      - 5555:5555
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
